### ISSUE TITLE
Clients don't remember manually-floated geometries

### ISSUE THREAD

**Issue by duckwork** [berlam/awesome-remember-geometry#1]
When I manually float a client by setting `c.floating = not c.floating`, the client floats in its tiled position, NOT its previously-floated position. Is this a desired function?

**Comment by berlam** [comment]
The plugin currently only handles layout changes to and from floating layouts on a tag.
But it think the current develop branch should satisfy your request: 3e7d39fbcade5bcddd71dddf3230882137c5c27f
I am not using mixed layouts, so just reply if you discover errors.

**Comment by berlam** [comment]
14 days past without answer. Closed.

**Comment by duckwork** [comment]
Hi @berlam, I am so sorry I haven't replied yet. I've fixed my Github notification settings, but I really am commenting here to thank you for the fix. It works perfectly! I hope it's okay I thank you on a closed issue.
